appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
shippable:
  projectId: 5c32e79b302eb707003c12ef
  secure: {BINSTAR_TOKEN: bkTdATvev7sVFsP62xFV2ck215nXEtH7eWXdhzRRtbzeKquSkNhTGTCoa5FcLDvAVe36w+Sv59/3/oWNyMood8pIWjHLMC5CqqLdc4NRmyyaCKWys4CLhTTurIBPFSWUilxZW1KCKv/WHOe+zQDi2o9R9lf5/MizuwThHSQOIcqeTIn4wtPzbne5MeKSW+mRCsb+l4E/Q1oY2w/mTJ+izDWkxefstZ2t8RqOxH6H20wwNOOj/1WdeztdCOtCAl99r8Aj58odGyfUMAEyw89c5HglAEPurBQs21DZbHp10NmgSLyIbukplulRUm+cQ37loT/hFfTjPUCqLEC3lu6SPw==}
travis:
  secure: {BINSTAR_TOKEN: S3GiDzPuGeng272jK4BN/L59s742jdf8A3QnWLViqvzyBWRdloh1tOpB7bEZNpttzocxMfoo2fvLPAUM7T50czBYHWSg9Zn7ZvwY9+qLCUlBLTv5et9ysnyEdtREkecfJ4AVegimnbVyhhkAAg/fbpHGuIQZbJP2TvXleqO/5Iqop4DTkN6L7F/4acSJNqPLYGlntnsVeIuIaHLkreOtf8zYPJD3USynwlMcoi/3FQ7ADkEd8ye4Xp7aAEKlwO3yW/SkcQG5TkkCkA6IZM2T1LanijURPACHM3ejZwS3+DviC+AHYR0bGOlJWj0KLjmvBzplswAQWynwMQSKmFfD5FEy4x/Ubk8Y7wf9uUX2sy8SE+EVSM0M4SVVTlxJHR7tTe6TUv55zRb6FBXPkCN8vgpNM9j2wwWtG2zUJbMlqV0sInPCq4/D3+3ZtQkv4JZmdUDMmaaEKyBFvlzHPX5DCUUk0LqMuMHVIL9lNz/JSCQdLCLPbrv8Sv6Tcf6wljHS2iQwpzaR+/v8CGoqYYF/rAmuNYBghbhj/nCfqk5jlSh/lqnge4JPn/+bDaki/pDbXBOrBYBjNt6+H2ZvKtJmKj3mcAPS61K3ZEdT9pF6IafPP9T6llIwYJ4kuRiGjAv9HX7TjcTmx4nx8Nnr0T472hxEV/Nln3WDu9qkyrdQwA4=}
